### ISSUE TITLE
JSON not showing the Prefix

### ISSUE THREAD

**Issue by MrCrispis** [SimpleBroadcast/SimpleBroadcast#28] opened 2016-04-02 14:11 UTC
Hello, I'll go straight forward to the problem.

When adding JSON messages, the prefix is not showing up.

Here is the config.yml:
http://pastebin.com/zutA4hid

As you can see, I have the prefix enabled.

Please fix it! :+1:

**Comment by ghost** [comment] 2016-04-03 20:33
Hello,

this is more or less an intended behaviour of v1.X.
This will get fixed in v2.X.

Kind regards,
KingDome24

**Closed as completed by ghost** 2016-04-03 20:33 UTC
Labels: invalid
